version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.back
    ports:
      - "3000:3000"
    environment:
      - secret=yoursecret
      - databaseurl=mongodb://mongo:27017/mydatabase
      # - MONGODB_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  frontend:
    build:
      context: . # Assuming your frontend code is in a folder named 'frontend'
      dockerfile: Dockerfile.front # You can also specify a different Dockerfile if needed
    ports:
      - "5173:5173"
    environment:
      - secret=yoursecret
      - databaseurl=mongodb://mongo:27017/mydatabase
    depends_on:
      - backend

volumes:
  mongo-data:
